/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;


/**
 *
 * @author Computador
 */
public class telaDeLoguin extends javax.swing.JFrame {

    /**
     * Creates new form telaDeLoguin
     */
    public telaDeLoguin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_titulo = new javax.swing.JTextField();
        jLabel_usuario = new javax.swing.JLabel();
        form_usuario = new javax.swing.JTextField();
        jLabel_senha = new javax.swing.JLabel();
        form_senha = new javax.swing.JTextField();
        jButton_entrar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_titulo.setBackground(new java.awt.Color(153, 0, 51));
        jTextField_titulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_titulo.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_titulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_titulo.setText("IMFORME SEU USUARIO E SENHA PARA ENTRAR");
        jTextField_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tituloActionPerformed(evt);
            }
        });

        jLabel_usuario.setBackground(new java.awt.Color(153, 0, 0));
        jLabel_usuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_usuario.setText("USUARIO");

        form_usuario.setBackground(new java.awt.Color(153, 0, 0));
        form_usuario.setForeground(new java.awt.Color(0, 0, 0));

        jLabel_senha.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_senha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_senha.setText("SENHA");

        form_senha.setBackground(new java.awt.Color(153, 0, 0));
        form_senha.setForeground(new java.awt.Color(0, 0, 0));
        form_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_senhaActionPerformed(evt);
            }
        });

        jButton_entrar.setBackground(new java.awt.Color(153, 0, 0));
        jButton_entrar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_entrar.setText("ENTRAR");
        jButton_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_entrarMouseClicked(evt);
            }
        });

        jButton_cancelar.setBackground(new java.awt.Color(153, 0, 0));
        jButton_cancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_cancelar.setText("CANCELAR");
        jButton_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(form_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_entrar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_cancelar))
                                .addComponent(form_senha)))))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_entrar)
                    .addComponent(jButton_cancelar))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tituloActionPerformed

    private void form_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_senhaActionPerformed
     
    }//GEN-LAST:event_form_senhaActionPerformed

    private void jButton_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cancelarMouseClicked
       System.exit(0);
    }//GEN-LAST:event_jButton_cancelarMouseClicked

    private void jButton_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_entrarMouseClicked
        // TODO add your handling code here:
        if ((form_usuario.getText().isEmpty()) || (form_senha.getText().isEmpty())) {
(null, "Preencha o campo Usuário e Senha”);
}else
        {
            
        }
        
    }//GEN-LAST:event_jButton_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDeLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDeLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDeLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDeLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDeLoguin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField form_senha;
    private javax.swing.JTextField form_usuario;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_entrar;
    private javax.swing.JLabel jLabel_senha;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JTextField jTextField_titulo;
    // End of variables declaration//GEN-END:variables
}
