/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import classes.NumeroNatural;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Computador
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_primeiroNumero = new javax.swing.JTextField();
        jTextField2_segundoNumero = new javax.swing.JTextField();
        jButton_Executar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabela = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PRIMEIRO NUMERO");

        jLabel2.setText("SEGUNDO NUMERO ");

        jTextField_primeiroNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_primeiroNumeroActionPerformed(evt);
            }
        });

        jButton_Executar.setText("EXECUTAR");
        jButton_Executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExecutarActionPerformed(evt);
            }
        });

        jTable1_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item ", "Primeiro Numero", "Segundo Numero"
            }
        ));
        jScrollPane1.setViewportView(jTable1_tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jTextField2_segundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_primeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addComponent(jButton_Executar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_primeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2_segundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Executar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_primeiroNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_primeiroNumeroActionPerformed
      

    }//GEN-LAST:event_jTextField_primeiroNumeroActionPerformed

    private void jButton_ExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExecutarActionPerformed
     
 try{
                   NumeroNatural primeiro = new NumeroNatural(Long.parseLong(jTextField_primeiroNumero.getText()));
            NumeroNatural segundo = new NumeroNatural(Long.parseLong(jTextField2_segundoNumero.getText()));
            
            
                  

            //tratamento try/catch fatorial
            //fonte miguel neto 
            String primeiroFatorial ;
            String segundoFatorial ;
            
            try {
                primeiroFatorial = primeiro.calcularFatorial().getNumero() + "";
            } catch (Exception e) {
                primeiroFatorial = e.getMessage();
            }
            
            try {
                segundoFatorial = segundo.calcularFatorial().getNumero()+ "";
            } catch (Exception e) {
                segundoFatorial = e.getMessage();
            }
            
            
          
            
                  
            // Tabela 
            
            DefaultTableModel model = (DefaultTableModel) jTable1_tabela.getModel();
            String[] linha = new String[3];
//esta parte da tabela mostra o fatorial
            linha[0] = "FATORIAL";
            linha[1] = "" + primeiroFatorial; 
            linha[2] = "" + segundoFatorial;
            model.addRow(linha);
//realiza o calculo mostrando se o numero e perfeito ou nao 
            linha[0] = "NÚMERO PERFEITO";
            if (primeiro.eNumeroPerfeito()) linha[1] = "SIM"; else linha[1] = "NÃO";
            if (segundo.eNumeroPerfeito())  linha[2] = "SIM"; else linha[2] = "NÃO";
            model.addRow(linha);
//mostra se o metodo tem procedencia de formato capicula 
            linha[0] = "CAPICUIA";
            if (primeiro.eCapicula()) linha[1] = "SIM"; else linha[1] = "NÃO";
            if (segundo.eCapicula())  linha[2] = "SIM"; else linha[2] = "NÃO";
            model.addRow(linha);
//verifica se o numero e um quadrado perfeito , pegado por base os numeros
            linha[0] = "QUADRADO PERFEITO";
            if (primeiro.eQuadradoPerfeito()) linha[1] = "SIM" ; else linha[1] = "NÃO";
            if (segundo.eQuadradoPerfeito())  linha[2] = "SIM";  else linha[2] = "NÃO";
            model.addRow(linha);
//verifica se os numeros sao primos ou nao 
            linha[0] = "NÚMERO PRIMO";
            if (primeiro.eNumeroPrimo()) linha[1] = "SIM"; else linha[1] = "NÃO";
            if (segundo.eNumeroPrimo()) linha[2] = "SIM"; else  linha[2] = "NÃO";
            model.addRow(linha);
//decimal 
            linha[0] = "BASE 10 PARA BASE 2";
            linha[1] = "" + primeiro.mudarBase(2);
            linha[2] = "" + segundo.mudarBase(2);
            model.addRow(linha);
//octagonal 
            linha[0] = "BASE 10 PARA BASE 8";
            linha[1] = "" + primeiro.mudarBase(8);
            linha[2] = "" + segundo.mudarBase(8);;
            model.addRow(linha);
//hexagonal
            linha[0] = "BASE 10 PARA BASE 16";
            linha[1] = "" + primeiro.mudarBase(16);
            linha[2] = "" + segundo.mudarBase(16);
            model.addRow(linha);
//macximo divisor comun               
            linha[0] = "MÁXIMO DIVISOR COMUM";
            linha[1] = "" + primeiro.calcularMDC(segundo).getNumero();
            linha[2] = "" + segundo.calcularMDC(primeiro).getNumero();
            model.addRow(linha);
//minimo multiplo comun 
            linha[0] = "MÍNIMO MÚLTIPLO COMUM";
            linha[1] = "" + primeiro.calcularMMC(segundo).getNumero();
            linha[2] = "" + segundo.calcularMMC(primeiro).getNumero();
            model.addRow(linha);
//numeros que sao primos entre si 
            linha[0] = "PRIMOS ENTRE SI";
            if (primeiro.saoPrimosEntreSi(segundo)) linha[1] = "SIM"; else linha[1] = "NÃO";
            if (segundo.saoPrimosEntreSi(primeiro))  linha[2] = "SIM"; else linha[2] = "NÃO";
            model.addRow(linha);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }


                                     
      

    
    }//GEN-LAST:event_jButton_ExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Executar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1_tabela;
    private javax.swing.JTextField jTextField2_segundoNumero;
    private javax.swing.JTextField jTextField_primeiroNumero;
    // End of variables declaration//GEN-END:variables
}
